# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-22 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('Date_Joiend', models.DateField(auto_now_add=True)),
                ('last_login', models.DateField(auto_now_add=True)),
                ('password', models.CharField(max_length=30)),
                ('confiem_password', models.CharField(max_length=30)),
            ],
        ),
    ]
